from PyInstaller.utils.hooks import collect_submodules
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['run_packaged.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('backend/app', 'app'),
        ('frontend/dist', 'frontend/dist'),
    ],
    hiddenimports=[
        'pydantic_settings',
        'sqlalchemy',
        'sqlalchemy.dialects.sqlite',
        'sqlalchemy.dialects.sqlite.aiosqlite',
        'aiosqlite',
        'greenlet',
        'fastapi.middleware.cors',
        'fastapi.staticfiles',
        'passlib.context',
        'passlib.hash.bcrypt',
        'passlib.hash.sha256_crypt',
        'jose',
        'jose.jwt',
        'jose.jws',
        'jose.jwe',
        'httpx',
        'PIL',
        'bcrypt',
        'python_multipart',
        'cryptography.fernet',
    ] + collect_submodules('passlib') + collect_submodules('jose'),
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'pytest',
        'mypy',
        'hypothesis',
        'IPython',
        'trio',
        'uvloop',
        'winloop',
        'psycopg2',
        'psycopg',
        'asyncpg',
        'pymysql',
        'mysql',
        'oracledb',
        'cx_Oracle',
        'gunicorn',
        'watchfiles',
        'wsproto',
        'werkzeug',
        'python_socks',
        'yaml',
        'passlib.tests',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='AIsChat',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='AIsChat',
)
